# frozen_string_literal: true

# Assuming you have not yet changed these files, each step below explains what
# you should configure. This file was generated by the `devise:install` generator
# and then customized for API-only mode with JWT.

# Devise configuration for API-only Rails application with JWT authentication.
# See https://github.com/heartcombo/devise for full configuration options.

Devise.setup do |config|
  # ==> ORM configuration
  require "devise/orm/active_record"

  # ==> Configuration for :database_authenticatable
  config.stretches = Rails.env.test? ? 1 : 12

  # ==> Configuration for :confirmable
  # config.reconfirmable = true

  # ==> Configuration for :rememberable
  # Not used in API-only mode — JWT handles session persistence.

  # ==> Configuration for any authentication mechanism
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]

  # ==> Navigation configuration
  # CRITICAL: Set to empty array for API-only mode.
  # This prevents Devise from trying to redirect to HTML sign-in pages.
  config.navigational_formats = []

  # ==> Sign out configuration
  config.sign_out_via = :delete

  # ==> Mailer Configuration
  config.mailer_sender = "noreply@crm-ecosystem.dev"

  # ==> Warden configuration
  # Tell Devise not to intercept 401 responses and redirect to login page.
  # Instead, it will return a 401 JSON response.
  config.warden do |manager|
    manager.failure_app = DeviseFailureApp
  end

  # ==> JWT Configuration (devise-jwt)
  config.jwt do |jwt|
    # Use Rails secret key base as the JWT signing key.
    # In production, consider using a dedicated JWT secret via credentials:
    #   Rails.application.credentials.dig(:devise, :jwt_secret_key)
    jwt.secret = Rails.application.credentials.secret_key_base

    # JWT token expiration time: 24 hours (1 day)
    jwt.expiration_time = 1.day.to_i

    # Dispatch JWT token on these requests (sign in / sign up)
    jwt.dispatch_requests = [
      ["POST", %r{^/api/v1/login$}],
      ["POST", %r{^/api/v1/signup$}]
    ]

    # Revoke JWT token on these requests (sign out)
    jwt.revocation_requests = [
      ["DELETE", %r{^/api/v1/logout$}]
    ]
  end

end
